apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: demo-test
  ports:
    - port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}

