apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm/demo
    repoURL: https://github.com/mvanderheijden/kennisdeling.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
