apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: demo-test
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080

